name: oe-alliance plugins

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build oe-alliance plugins
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: ['3.10','3.11','3.12','3.13','3.14']
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get install -y autoconf automake gettext

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Build plugins, python ${{ matrix.python }}
        run: |
          autoreconf -i
          ./configure
          make
          make install DESTDIR=$PWD/install
          python -W error -m compileall -q .
