name: oe-alliance plugins

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build oe-alliance plugins
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.10','3.11','3.12','3.13']
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install -y build-essential autoconf gettext python${{ matrix.python }}-dev libntirpc-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build plugins, python ${{ matrix.python }}
        run: |
          autoreconf -i
          ./configure
          make
          python -m compileall .
